### PR TITLE
Create lt

### PR DESCRIPTION
**Pull request by andiukas**

### CODE REVIEW

**Comment by ngocjohn** [comment]
Hi, thanks for PR. can you add a .json extension for the file? 😄

**Comment by andiukas** [comment]
[lt.json](https://github.com/user-attachments/files/16541545/lt.json)

**Comment by ngocjohn** [comment]
I'll pull later and rename the file, thanks for sharing.

**Comment by ngocjohn** [comment]
I'm sorry, I changed the way the translation was processed. Can you please pull a new commit and it will have lt.json directly in src/languages folder. Please add new translations and create a new PR with this change, thanks in advance for improving this card.

**Pull request closed without merging**
